// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrinjlurkhhyfknimnmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyaW5qbHVya2hoeWZrbmltbm1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTUwNzksImV4cCI6MjA1OTY3MTA3OX0.C1-Jv-1ExJwNO7cGqTMcRMVQF9zYfjv_yniGR5Hxv68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);